- name: demo on filters
  hosts: localhost
  vars: 
    NAME: Udaykiran Yemineni
    website: https://github.com/devops-uday/ansible-advanced
    greeting: Hello Uday, welcome to DEVOPS
  tasks:
  - name: convert into upper case
    debug:
      msg: "hello {{NAME | upper}}"

  - name: convert into lower case
    debug:
      msg: "hello {{NAME | lower}}"

  - name: printing undefined variable
    debug:
      msg: "course is {{COURSE | default('Devops')}}"

  - name: extract hostname
    debug:
      msg: "hostname is {{website | urlsplit('hostname')}}"

  - name: split
    debug: 
      msg: "splitting {{greeting | split(',')}}"
