- name: demo on filters
  hosts: localhost
  vars: 
    NAME: Udaykiran Yemineni
  tasks:
  - name: convert into upper case
    debug:
      msg: "hello {{NAME | upper}}"

  - name: convert into lower case
    debug:
      msg: "hello {{NAME | lower}}"
